name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: latest
      - run: bb test
      - run: bb golden
      - run: ./scripts/launcher.sh
